name: "CI - Shell Linter"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Shell Linter
        uses: azohra/shell-linter@v0.8.0
        with:
          path: "src/**/*.sh test/**/*.sh"
          severity: "warning"
